version: "3.7"

services:
  prod-kube-cluster:
    image: jkostov/kube-cluster
    container_name: prod-kube-cluster
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - APP_PORT=3000
      - KAFKA_URL=prod-kube-kafka:9092
      - MONGO_URL=mongodb://root:root1234@prod-kube-cluster-mongo:27017/database
    depends_on:
      - prod-kube-cluster-mongo
      - prod-kube-kafka

  prod-kube-cluster-mongo:
    image: jkostov/mongo:4.2
    container_name: prod-kube-cluster-mongo
    expose:
      - "27017"
    volumes:
      - prod-kube-cluster-mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root1234
      - MONGO_INITDB_DATABASE=database

  prod-kube-resource:
    image: jkostov/kube-resource
    container_name: prod-kube-resource
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - APP_PORT=3001
      - KAFKA_URL=prod-kube-kafka:9092
      - MONGO_URL=mongodb://root:root1234@prod-kube-resource-mongo:27017/database
    depends_on:
      - prod-kube-resource-mongo
      - prod-kube-kafka

  prod-kube-resource-mongo:
    image: jkostov/mongo:4.2
    container_name: prod-kube-resource-mongo
    expose:
      - "27017"
    volumes:
      - prod-kube-resource-mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root1234
      - MONGO_INITDB_DATABASE=database

  prod-kube-frontend:
    image: jkostov/kube-frontend
    container_name: prod-kube-frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development

  prod-kube-zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: prod-kube-zookeeper
    ports:
      - "2181:2181"

  prod-kube-kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    container_name: prod-kube-kafka
    expose:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: prod-kube-zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: prod-kube-kafka

volumes:
  prod-kube-cluster-mongo-data: {}
  prod-kube-resource-mongo-data: {}
