apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kube-ingress
spec:
  rules:
    - host: kube-app.test
      http:
        paths:
          - path: /
            backend:
              serviceName: kube-frontend
              servicePort: 80
          - path: /cluster
            backend:
              serviceName: kube-cluster
              servicePort: 3000
          - path: /resource
            backend:
              serviceName: kube-resource
              servicePort: 3001
