apiVersion: v1
kind: Service
metadata:
  name: kube-kafka
  labels:
    app: kube-kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kube-kafka

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-kafka
  labels:
    app: kube-kafka
spec:
  selector:
    matchLabels:
      app: kube-kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-kafka
    spec:
      hostname: kube-kafka
      containers:
        - name: kube-kafka
          image: wurstmeister/kafka:2.12-2.4.0
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: kube-zookeeper:2181
            - name: KAFKA_LISTENERS
              value: LISTENER_TEST://kube-kafka:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: LISTENER_TEST://kube-kafka:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: LISTENER_TEST:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: LISTENER_TEST
